-- ES 同步待补标记：索引失败时置位，后台重试成功后清除
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS es_pending BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ports ADD COLUMN IF NOT EXISTS es_pending BOOLEAN NOT NULL DEFAULT FALSE;
